version: "3.1"
services:
  mariadb:
    image: mariadb:10.4
    container_name: dev-mariadb
    command: mysqld --max_allowed_packet=1073741824 --sql_mode=""
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - dev-mysql-data:/data
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=forge
      - MYSQL_USER=forge
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

# Volumes
volumes:
  dev-mysql-data:
